title: Sandria Amelia Putri
logo: /assets/img/profile.png
description: An undergraduate data science student. Leveraging analytics skills for valuable insights and being enthusiastic about effective decision-making.
#show_downloads: true
theme: jekyll-theme-minimal
